version: '3.1'

networks:
  iisrc-bridge:
    external: true

services:
  mongo:
    image: taehoony/mongo:1.4
    container_name : KETI_IISRC_Mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - /home/keti3dp/disks/disk0/data/mongo_IISRC/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: keti_root
      MONGO_INITDB_ROOT_PASSWORD: madcoder
    networks:
      iisrc-bridge:
        ipv4_address: ${MONGO_IP}